version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: vulnscan_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: vulnscan_web
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: gunicorn -b 0.0.0.0:5000 app:app